#!/bin/bash

# Test script for POD install

if [ ! -e ~/pod ]; then 
  echo "No sym link to the pod root directory"
  echo "In you home dorectory create a sym link to the pod root directory"
  echo "Eg: cd ~; ln -s /data/software/acs/pod pod"
  exit
fi

# Clean up old files
./ex1.clean
 
# Create necessary links
ln -s ~/pod/tables/ascp1950.430 .             >& /dev/null
ln -s ~/pod/tables/fes2004_Cnm-Snm.dat .      >& /dev/null
ln -s ~/pod/tables/goco05s.gfc .              >& /dev/null
ln -s ~/pod/tables/header.430_229 .           >& /dev/null
ln -s ~/pod/tables/igs_metadata_2063.snx .    >& /dev/null
ln -s ~/pod/tables/leap.second .              >& /dev/null
ln -s ~/pod/tables/eopc04_14_IAU2000.62-now . >& /dev/null

# Run the POD
~/pod/bin/pod | tee pod.out

echo 'Plotting: 1] orbit fit residual time series'
python3 ~/pod/scripts/res_plot.py     -i gag19424_igs19424_orbdiff_rtn.out -d . -c G >& /dev/null
echo '          2] orbit fit statistics'
python3 ~/pod/scripts/rms_bar_plot.py -i gag19424_igs19424_orbdiff_rtn.out -d . -c G >& pod.rms

# Diff output
diff pod.out ./solution/pod.out
diff pod.rms ./solution/pod.rms
diff gag19424.sp3 ./solution/gag19424.sp3

# Cleanup 
\rm -r EQM0* VEQ0* ECOM1_*.in emp*.in DE.430 

exit 
